Games:
  CorporateClash:
    prefix: "~/.wine"
    token_api: "https://corporateclash.net/api/launcher/v1/register"
    login_api: "https://corporateclash.net/api/launcher/v1/login"
    gameserver: "https://gs.corporateclash.net"
    default_district: "Seltzer Summit"

  ToontownRewritten:
    prefix: "~/.ttr"
    api_path: "https://www.toontownrewritten.com/api/login?format=json"

GameData:
  clash:
    uses_password: 0
  rewritten:
    uses_password: 1

Handlers:
  Windows:
    wine_executable: "wine"
